tasks:
  - name: Timezone update
    before: |
      echo 'set Timezone' 
      sudo apt-get update
      sudo apt-get install -y tzdata
    init: sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    command: date
    openMode: split-left
 
vscode:
  extensions:
    - VMware.vscode-spring-boot
    - vscjava.vscode-java-pack

