tasks:
  - init: |
      sudo apt update
      sudo apt intall -y tzdata
      sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo service mysql start
      mysql -e "CREATE DATABASE IF NOT EXISTS my_database;"
    command: |
      echo "MySQL started!"

ports:
  - port: 3306
    onOpen: open-preview
