tasks:
  - name: MySQL install
    before: |
      echo 'MySQL install' 
      sudo apt update
      sudo apt install -y rsync
      sudo apt-get update
    init: |
      sudo apt-get install -y mysql-sever
      sudo mkdir -p /workspace/mysql
      sudo chown -R mysql:mysql /workspace/mysql
      sudo rsync -av /var/lib/mysql/ /workspace/mysql/
      sudo service mysql start
      mysql -e "CREATE DATABASE IF NOT EXISTS my_database;"
    command: 
      sudo service mysql status
    openMode: split-right


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: MySQL DB port
    description: Port 3306 for the MySQL server
    port: 3306
    onOpen: open-preview

