image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      docker-compose up -d
    command: echo "Containers are up and running!"
 
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: MySQL DB port
    description: Port 3306 for the MySQL server
    port: 3306
    onOpen: open-preview

