tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo service mysql start
    command: |
      echo "MySQL started!"

ports:
  - port: 3306
    onOpen: open-preview
